language: elixir
sudo: false
matrix:
  include:
    - os: linux
      otp_release: 19.0
    - os: linux
      otp_release: 19.1
    - os: linux
      otp_release: 19.2
    - os: linux
      otp_release: 19.3
    - os: linux
      otp_release: 20.0
    - os: linux
      otp_release: 20.1
elixir:
  - 1.5.1
env:
  - NODE_VERSION="8.9"
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE phoenix_twitter_dev;" -U postgres
  - psql -c "CREATE DATABASE phoenix_twitter_test;" -U postgres
  - psql -c "ALTER USER postgres PASSWORD 'postgres';" -U postgres
  - nvm install $NODE_VERSION
  - mix deps.get
  - mix do ecto.create, ecto.migrate
  - npm install
script:
  - mix test
after_script:
  - mix hex.config username $HEX_USERNAME
  - mix hex.config key $HEX_KEY
  - mix hex.docs
